language: node_js
node_js:
  - 12
  - 11
  - 10

cache: yarn

install:
  - yarn 
  - yarn build
  - yarn bootstrap
  - cd packages/tm-cli && npm link

script:
  - yarn test

after_script:
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - yarn release