language: node_js
node_js:
  - 12
  - 11
  - 10

# cache: yarn

install:
  - yarn
  - yarn bootstrap
  - yarn build

script:
  - yarn test

after_script:
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - yarn release