language: node_js
node_js:
  - 12
  - 11
  - 10

cache: yarn

install:
  - yarn add typescript@3.9.5 -D
  - yarn 
  - yarn build
  - npm link

script:
  - yarn test

after_script:
  - bash <(curl -s https://codecov.io/bash)